/*
 * Automatically generated by Magic
 */
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { marker } from '@biesbjerg/ngx-translate-extract-marker';

import { HomeComponent } from './home.component';
import { Shell } from '@app/shell/shell.service';
import { UserManagementComponent } from '@app/common/user-management/user-management.component';

// Then importing all CRUD components.
import { Customers_customersComponent } from '../components/Customers/customers/Customers_customers.component';
import { Customers_GoodsComponent } from '../components/Customers/Goods/Customers_Goods.component';


const routes: Routes = [
  Shell.childRoutes([
    { path: '', component: HomeComponent, data: { title: marker('Home') } },
    { path: 'users', component: UserManagementComponent, data: { title: marker('User management') } },

    // Then routes for all CRUD components.
    { path: 'crud/Customers/customers', component: Customers_customersComponent, data: { title: marker('Customers/customers') } },
    { path: 'crud/Customers/Goods', component: Customers_GoodsComponent, data: { title: marker('Customers/Goods') } },

  ]),
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule],
  providers: [],
})
export class HomeRoutingModule {}
